server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      import: optional:configserver:http://localhost:8888   # Import du Config Server
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
