server:
  port: 8082

spring:
  application:
    name: book-service
  config:
    import: "optional:http://config-service:8888"
  datasource:
    url: jdbc:mysql://mysql-book:3306/bookdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
