server:
  port: 8082

spring:
  application:
    name: book-service

  config:
    import: "optional:configserver:http://config-service:8888"

  cloud:
    config:
      retry:
        max-attempts: 6        # nombre maximum de tentatives
        initial-interval: 2000 # intervalle initial en ms
        multiplier: 1.5        # facteur multiplicatif pour l’intervalle
        max-interval: 10000

  datasource:
    url: jdbc:mysql://mysql-book:3306/bookdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
