server:
  port: 8083

spring:
  application:
    name: order-service

  config:
    import: "optional:configserver:http://localhost:8083"
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
