# spring-cloud-config-repo/book-service.yml
server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  message: "Hello from Book Service Config 📚"