# spring-cloud-config-repo/book-service.yml
server:
  port: 8081

spring:
  application:
    name: user-service

  config:
    import: "optional:configserver:http://localhost:8082"
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

custom:
  message: "Hello from Book Service Config 📚"