# spring-cloud-config-repo/book-service.yml
server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true       # pour s’enregistrer
    fetch-registry: true             # pour récuperer la liste des services
    service-url:
      defaultZone: http://localhost:8761/eureka   # URL du serveur Eureka
  instance:
    prefer-ip-address: true          # affichage par IP au lieu du hostname

custom:
  message: "Hello from Book Service Config 📚"